version: '3'

services:
  db:
    platform: linux/x86_64/v8
    image: amd64/postgres:10
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_autoimport:/docker-entrypoint-initdb.d/
    networks:
      - postgres_network

  webapp:
    platform: linux/x86_64/v8
    build: ./mysite_project
    container_name: webapp
    env_file: .env
    command: gunicorn -w 3 -b :8000 site_core.wsgi
    volumes:
      - mysite_project:/code/
      - static_volume:/var/www/django/static
      - media_volume:/var/www/django/media
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - db

  nginx:
    platform: linux/x86_64/v8
    image: amd64/nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/django/static
      - media_volume:/var/www/django/media
    ports:
      - 8000:80
    depends_on:
      - webapp
    networks:
      - nginx_network


volumes:
  postgres_data:
  mysite_project:
  static_volume:
  media_volume:


networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
