version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  webapp:
    build: ./mysite_project
    command: gunicorn site_core.wsgi
    volumes:
      - mysite_project:/code/
    ports:
      - 8000:8000
    env_file:
      - ./secret_keys.env
    depends_on:
      - db

volumes:
  postgres-data:
  mysite_project:
