version: '3'

services:
  db:
    image: postgres
  webapp:
    build: ./mysite_project
    command: python3 manage.py makemigrations vue_test --settings=site_core.settings.development
    command: python3 manage.py makemigrations polls --settings=site_core.settings.development
    command: python3 manage.py makemigrations etextbook --settings=site_core.settings.development
    command: python3 manage.py makemigrations contact --settings=site_core.settings.development
    command: python3 manage.py makemigrations ajax_polls --settings=site_core.settings.development
    command: python3 manage.py migrate --settings=site_core.settings.development
    command: python3 manage.py createsuperuser --settings=site_core.settings.development
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=site_core.settings.development
    
    volumes:
      - ./mysite_project:/code/
    ports:
      - 8000:8000
    depends_on:
      - db
