version: '3'


services:
  db:
    image: postgres
    container_name: DjangoSitePostgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network

  webapp:
    build: ./mysite_project
    container_name: DjangoSiteDjango
    command: gunicorn --bind :8000 site_core.wsgi:application
    volumes:
      - mysite_project:/code/
      - static_volume:/var/www/django/static
      - media_volume:/var/www/django/media
    env_file:
      - ./secret_keys.env
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - db


  nginx:
    image: nginx:latest
    container_name: DjangoSiteNginx
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/django/static
      - media_volume:/var/www/django/media
    ports:
      - 8000:80
    depends_on:
      - webapp
    networks:
      - nginx_network


volumes:
  postgres-data:
  mysite_project:
  static_volume:
  media_volume:


networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge