version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  webapp:
    build: ./mysite_project
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=site_core.settings.development
    volumes:
      - mysite_project:/code/
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres-data:
  mysite_project: